config/routes.rb
Rails.application.routes.draw do
  resources :ideas

  root 'ideas#index'

end

app/models/idea.rb
class Idea < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:name, :description, :material, :tags, :font, :public)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_form.html.erb
<%= tinymce %>

<%= form_for(@idea, {:html => {:class => "ls-form row" }}) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<BR><BR>
<fieldset>
  <div class="ls-label col-md-7">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  
  <div class="ls-label">
    <%= f.text_area :description, :class => "tinymce", :rows => 30%>
  </div>

  <div class="ls-form ls-form-horizontal row">
    <div class="ls-label col-md-5 col-xs-12">
      <%= f.label :material %>
      <%= f.text_field :material %>
    </div>
    <div class="ls-label col-md-5 col-xs-12">
      <%= f.label :tags %>
      <%= f.text_field :tags %>
    </div>
    <div class="ls-label col-md-5">
      <%= f.label :font %>
      <%= f.text_field :font %>
    </div>
    <div class="ls-label col-md-5">
      <%= f.label :public, :class=>"ls-label-text"%>
      <%= f.check_box :public %>  
    </div>

</div>
  

</fieldset>
  <div class="ls-actions-btn">
  <%= f.submit "Send",  :class=>"ls-btn-primary" %>

<% end %>

app/views/ideas/edit.html.erb
<h1 class="ls-title-intro ls-ico-pencil">Edit Idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea, :class=>"ls-btn" %> 
<%= link_to 'Back', ideas_path, :class=>"ls-btn" %>
<%= link_to t(:destroy), @idea, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"ls-btn-danger" %>

<!-- END DIV back button -->
</div>

app/views/ideas/index.html.erb
<h1 class="ls-title-intro ls-ico-lamp">Lista de idéias</h1>

  <% @ideas.each do |idea| %>
  <div class="ls-list">
    <header class="ls-list-header">
      <div class="ls-list-title col-md-4">
        <table>
          <tr>
            <td>
              <p><h2><%= idea.name %></h2></p>
              <small><%= idea.material %></small>
            </td>
            <td valign="top"> 
              <% if idea.public %>
                <div class="ls-tag-success">public</div>
              <% else %>
                <div class="ls-tag-danger">private</div>
              <% end %>
            </td>
          </tr>
        </table>
      </div>
      <div class="col-md-3 col-md-offset-5 ls-txt-right">
        <%= link_to 'Show', idea, :class=>"ls-btn-primary" %>
      </div>   
    </header>
  </div>
<% end %>
<br>

<div class="ls-actions-btn">
  <%= link_to 'New Idea', new_idea_path, :class=>"ls-btn" %>
</div>

app/views/ideas/new.html.erb
<h1 class="ls-title-intro ls-ico-lamp">Add Idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path, :class=>"ls-btn" %>

<!-- END DIV back button -->
</div>

app/views/ideas/show.html.erb
<h1 class="ls-title-intro ls-ico-docs">Show Idea</h1>
<p id="notice"><%= notice %></p>

<div class="ls-box ls-box-gray">
  <h5 class="ls-title-2"><%= @idea.name %>
    <% if @idea.public %>
      <div class="ls-tag-success">
        PROJETO PUBLICO
      </div>
    <% else %>
      <div class="ls-tag-danger">
        PROJETO PRIVADO
      </div>
    <% end %>
  </h5>
</div>

<div class="ls-box">
  <p>
    <%= raw(@idea.description) %>
  </p>
</div>

<div class="ls-box">
  <h3 class="ls-title-5">Material: </h3>
  <p><%= @idea.material %></p>
</div>

<div class="ls-box">
  <h5 class="ls-title-5">Tags: </h5>
  <p><%= @idea.tags %></p>
</div>

<div class="ls-box">
  <h5 class="ls-title-5">Font: </h5>
  <p>
    <%= @idea.font %>
  </p>
</div>



<div class="ls-actions-btn">
  <%= link_to 'Edit', edit_idea_path(@idea), :class=>"ls-btn" %> 
  <%= link_to 'Back', ideas_path, :class=>"ls-btn" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="ls-theme-green">
  <head>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= tinymce_assets %>
    <script type="text/javascript" src="/assets/tinymce.js"> </script>
	  <%= csrf_meta_tags %>
    <title>Página com a estrutura inicial</title>

    <meta charset="utf-8">
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <meta name="description" content="Insira aqui a descrição da página.">
    <link href="http://assets.locaweb.com.br/locastyle/3.0.0/stylesheets/locastyle.css" rel="stylesheet" type="text/css">

  </head>
  <body>
    <div class="ls-topbar">

      <!-- Notification bar -->
      <div class="ls-notification-topbar">
        <!-- Link of support/help -->
        <div class="ls-alerts-list">
          <a href="#" class="ls-ico-bell-o" data-counter="5" data-ls-module="topbarCurtain" data-target="#ls-notification-curtain"><span>Notificações</span></a>
          <a href="#" class="ls-ico-bullhorn" data-ls-module="topbarCurtain" data-target="#ls-help-curtain"><span>Ajuda</span></a>
          <a href="#" class="ls-ico-question" data-ls-module="topbarCurtain" data-target="#ls-feedback-curtain"><span>Sugestões</span></a>
        </div>

        <!-- User details -->
        <div data-ls-module="dropdown" class="ls-dropdown ls-user-account">
          <a href="#" class="ls-ico-user">
            Douglas Campos
          </a>
          <nav class="ls-dropdown-nav ls-user-menu">
            <ul>
              <li><a href="#">Conta</a></li>
              <li><a href="#">Logout</a></li>
            </ul>
          </nav>
        </div>
      </div>

      <span class="ls-show-sidebar ls-ico-menu"></span>
      <span class="ls-show-notifications ls-ico-question"></span>

      <!-- Nome do produto/marca -->
      <h1 class="ls-brand-name"><a class="ls-ico-earth" href="/ideas">Ideas</a></h1>
    </div>

    <main class="ls-main ">
      <div class="container-fluid">
        
        <%= yield %>

      </div>
    </main>

    <aside class="ls-sidebar">
      <!-- Defails of user account -->
      <div data-ls-module="dropdown" class="ls-dropdown ls-user-account">
        <a href="#" class="ls-ico-user">
          Denis Hall
          <small>(lstyle)</small>
        </a>
        <nav class="ls-dropdown-nav ls-user-menu">
          <ul>
            <li><a href="#">submenu</a></li>
          </ul>
        </nav>
      </div>

      <nav class="ls-menu">
        <ul>
          <li>
            <%= link_to "Lista de Idéias",root_path, :class => "ls-ico-lamp" %>
          </li>
        </ul>
      </nav>
    </aside>

    <aside class="ls-notification">
      <nav class="ls-notification-list" id="ls-notification-curtain" style="left: 1716px;">
        <h3 class="ls-title-2">Notificações</h3>
        <ul>
          <li class="ls-dismissable">
            <a href="#">Blanditiis est est dolorem iure voluptatem eos deleniti repellat et laborum consequatur</a>
            <a href="#" data-ls-module="dismiss" class="ls-ico-close ls-close-notification"></a>
          </li>
          <li class="ls-dismissable">
            <a href="#">Similique eos rerum perferendis voluptatibus</a>
            <a href="#" data-ls-module="dismiss" class="ls-ico-close ls-close-notification"></a>
          </li>
          <li class="ls-dismissable">
            <a href="#">Qui numquam iusto suscipit nisi qui unde</a>
            <a href="#" data-ls-module="dismiss" class="ls-ico-close ls-close-notification"></a>
          </li>
          <li class="ls-dismissable">
            <a href="#">Nisi aut assumenda dignissimos qui ea in deserunt quo deleniti dolorum quo et consequatur</a>
            <a href="#" data-ls-module="dismiss" class="ls-ico-close ls-close-notification"></a>
          </li>
          <li class="ls-dismissable">
            <a href="#">Sunt consequuntur aut aut a molestiae veritatis assumenda voluptas nam placeat eius ad</a>
            <a href="#" data-ls-module="dismiss" class="ls-ico-close ls-close-notification"></a>
          </li>
        </ul>
      </nav>

      <nav class="ls-notification-list" id="ls-help-curtain" style="left: 1756px;">
        <h3 class="ls-title-2">Feedback</h3>
        <ul>
          <li><a href="#">&gt; quo fugiat facilis nulla perspiciatis consequatur</a></li>
          <li><a href="#">&gt; enim et labore repellat enim debitis</a></li>
        </ul>
      </nav>

      <nav class="ls-notification-list" id="ls-feedback-curtain" style="left: 1796px;">
        <h3 class="ls-title-2">Ajuda</h3>
        <ul>
          <li class="ls-txt-center hidden-xs">
            <a href="#" class="ls-btn-dark ls-btn-tour">Fazer um Tour</a>
          </li>
          <li><a href="#">&gt; Guia</a></li>
          <li><a href="#">&gt; Wiki</a></li>
        </ul>
      </nav>
    </aside>

    <!-- We recommended use jQuery 1.10 or up -->
    <script type="text/javascript" src="http://code.jquery.com/jquery-2.0.3.min.js"></script>
    <script src="http://assets.locaweb.com.br/locastyle/3.0.0/javascripts/locastyle.js" type="text/javascript"></script>
  </body>
</html>